# Generated by Django 4.0.3 on 2026-05-22 19:01

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer_type', models.CharField(choices=[('Residencial', 'Residencial'), ('Comercial', 'Comercial'), ('Industrial', 'Industrial')], max_length=32, verbose_name='Tipo de Consumidor')),
                ('consumption_range', models.CharField(choices=[('until_10000', '< 10.000 kWh'), ('between_10000_and_20000', '>= 10.000 kWh e <= 20.000 kWh'), ('above_20000', '> 20.000 kWh')], max_length=32, verbose_name='Faixa de Consumo')),
                ('coverage', models.DecimalField(choices=[(Decimal('90.00'), '90%'), (Decimal('95.00'), '95%'), (Decimal('99.00'), '99%')], decimal_places=2, help_text='Percentual de cobertura. Exemplo: 90.00 para 90%', max_digits=5, verbose_name='Cobertura')),
                ('discount', models.DecimalField(decimal_places=2, help_text='Percentual de desconto. Exemplo: 18.00 para 18%', max_digits=5, verbose_name='Desconto')),
            ],
            options={
                'verbose_name': 'Regra de Desconto',
                'verbose_name_plural': 'Regras de Desconto',
            },
        ),
        migrations.AlterField(
            model_name='consumer',
            name='distributor_tax',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Tarifa da Distribuidora'),
        ),
        migrations.AddConstraint(
            model_name='discountrule',
            constraint=models.UniqueConstraint(fields=('consumer_type', 'consumption_range'), name='unique_discount_rule_by_type_and_range'),
        ),
        migrations.AddField(
            model_name='consumer',
            name='discount_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumers', to='calculator.discountrule', verbose_name='Regra de Desconto'),
        ),
    ]
