# Generated by Django 4.0.3 on 2026-05-22 19:01

from decimal import Decimal

from django.db import migrations


DISCOUNT_RULES = [
    ("Residencial", "until_10000", Decimal("90.00"), Decimal("18.00")),
    ("Comercial", "until_10000", Decimal("90.00"), Decimal("16.00")),
    ("Industrial", "until_10000", Decimal("90.00"), Decimal("12.00")),
    ("Residencial", "between_10000_and_20000", Decimal("95.00"), Decimal("22.00")),
    ("Comercial", "between_10000_and_20000", Decimal("95.00"), Decimal("18.00")),
    ("Industrial", "between_10000_and_20000", Decimal("95.00"), Decimal("15.00")),
    ("Residencial", "above_20000", Decimal("99.00"), Decimal("25.00")),
    ("Comercial", "above_20000", Decimal("99.00"), Decimal("22.00")),
    ("Industrial", "above_20000", Decimal("99.00"), Decimal("18.00")),
]


def create_discount_rules(apps, schema_editor):
    DiscountRule = apps.get_model("calculator", "DiscountRule")

    for consumer_type, consumption_range, coverage, discount in DISCOUNT_RULES:
        DiscountRule.objects.update_or_create(
            consumer_type=consumer_type,
            consumption_range=consumption_range,
            defaults={
                "coverage": coverage,
                "discount": discount,
            },
        )


def delete_discount_rules(apps, schema_editor):
    DiscountRule = apps.get_model("calculator", "DiscountRule")
    DiscountRule.objects.filter(
        consumer_type__in=["Residencial", "Comercial", "Industrial"],
        consumption_range__in=[
            "until_10000",
            "between_10000_and_20000",
            "above_20000",
        ],
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_discountrule_alter_consumer_distributor_tax_and_more'),
    ]

    operations = [
        migrations.RunPython(create_discount_rules, delete_discount_rules),
    ]
