# Generated by Django 4.0.3 on 2026-05-22 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_seed_discount_rules'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='discountrule',
            name='unique_discount_rule_by_type_and_range',
        ),
    ]
